language: go

install:
  - go get -u github.com/golang/lint/golint
  # This is default if `install` not overridden:
  - go get -t -v ./...

before_script:
  - ./check_gofmt.sh
  - go vet ./...
  - golint -set_exit_status ./...

script: go test -v -race ./...
before_deploy:
  - PLATFORMS=(darwin/386 darwin/amd64 freebsd/386 freebsd/amd64 freebsd/arm linux/386 linux/amd64 linux/arm windows/386 windows/amd64)
 # build binary for all archs
  - go get -u ./...
  - |
    for PLATFORM in "${PLATFORMS[@]}"; do
      echo "Building $PLATFORM"
      GOOS=${PLATFORM%/*}
      GOARCH=${PLATFORM#*/}
      if [ "$GOOS" = "windows" ]; then
        build_cmd="GOOS=$GOOS GOARCH=$GOARCH go build -o kafka_consumer_group_exporter -ldflags '-w -s' ./cmd/prometheus-kafka-consumer-group-exporter/kafka_consumer_group_exporter.go"
      else
        build_cmd="CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o kafka_consumer_group_exporter -ldflags '-d -w -s' ./cmd/prometheus-kafka-consumer-group-exporter/kafka_consumer_group_exporter.go"
      fi
      if ! eval $build_cmd; then
        echo "Failed building kafka_consumer_group_exporter for $PLATFORM" && return 1
      fi
      if [ "$GOOS" = "windows" ]; then
        zip kafka_consumer_group_exporter-${GOOS}-${GOARCH}.zip kafka_consumer_group_exporter
      else
        tar cvzf kafka_consumer_group_exporter-${GOOS}-${GOARCH}.tgz kafka_consumer_group_exporter
      fi
    done
  - ls
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file:
    - "kafka_consumer_group_exporter-darwin-386.tgz"
    - "kafka_consumer_group_exporter-darwin-amd64.tgz"

    - "kafka_consumer_group_exporter-freebsd-386.tgz"
    - "kafka_consumer_group_exporter-freebsd-arm.tgz"
    - "kafka_consumer_group_exporter-freebsd-amd64.tgz"

    - "kafka_consumer_group_exporter-linux-386.tgz"
    - "kafka_consumer_group_exporter-linux-arm.tgz"
    - "kafka_consumer_group_exporter-linux-amd64.tgz"

    - "kafka_consumer_group_exporter-windows-386.zip"
    - "kafka_consumer_group_exporter-windows-amd64.zip"
  on:
    tags: yes
